#!/usr/bin/env python3
"""Generate <Network>Sionna wrapper NEDs that add a SionnaManager to existing
Simu5G networks, so any static scenario can be run with the Sionna channel model
(Plan A) without editing the original network.

Usage:
    sionnaize.py simu5g.simulations.nr.networks.MultiCell_Standalone [more...]

Writes <Name>Sionna.ned into ./generated/ (package
simu5g.simulations.nr.sionna.generated). Pair it with sionna-common.ini:

    [Config X-Sionna]
    extends = <original config>
    include ../sionna/sionna-common.ini
    network = simu5g.simulations.nr.sionna.generated.<Name>Sionna
"""
import os
import sys

TEMPLATE = """//
// Auto-generated by sionnaize.py - do not edit by hand.
// {fqn}  ->  {name}Sionna  (adds a global SionnaManager for Plan A).
//
package simu5g.simulations.nr.sionna.generated;

import {fqn};
import simu5g.stack.phy.channelmodel.sionna.SionnaManager;

network {name}Sionna extends {name}
{{
    submodules:
        sionnaManager: SionnaManager {{
            @display("p=50,341;is=s");
        }}
}}
"""


def main(argv):
    if len(argv) < 2:
        sys.stderr.write(__doc__)
        return 2
    outdir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "generated")
    os.makedirs(outdir, exist_ok=True)
    for fqn in argv[1:]:
        name = fqn.rsplit(".", 1)[-1]
        path = os.path.join(outdir, name + "Sionna.ned")
        with open(path, "w") as f:
            f.write(TEMPLATE.format(fqn=fqn, name=name))
        print("wrote", path, "->", "simu5g.simulations.nr.sionna.generated."
              + name + "Sionna")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
