//
//                  Simu5G
//
// Authors: Giovanni Nardini, Giovanni Stea, Antonio Virdis (University of Pisa)
//
// This file is part of a software released under the license included in file
// "license.pdf". Please read LICENSE and README files before using it.
// The above files and the present reference are part of the software itself,
// and cannot be removed from it.
//

#ifndef __SIMU5G_INITSTAGES_H
#define __SIMU5G_INITSTAGES_H

#include <inet/common/InitStages.h>

//
// INET stages:
//
// LOCAL = 0
// NETWORK_INTERFACE_CONFIGURATION = 1
// POWER = 2
// GROUP_MOBILITY = 3
// PHYSICAL_ENVIRONMENT = 4
// CLOCK = 5
// SINGLE_MOBILITY = 6
// PHYSICAL_OBJECT_CACHE = 7
// PHYSICAL_LAYER = 8
// LINK_LAYER = 9
// GATE_SCHEDULE_CONFIGURATION = 10
// PHYSICAL_LAYER_NEIGHBOR_CACHE = 11
// NETWORK_CONFIGURATION = 12
// QUEUEING = 13
// NETWORK_ADDRESS_ASSIGNMENT = 14
// ROUTER_ID_ASSIGNMENT = 15
// STATIC_ROUTING = 16
// NETWORK_LAYER = 17
// NETWORK_LAYER_PROTOCOLS = 18
// TRANSPORT_LAYER = 19
// ROUTING_PROTOCOLS = 20
// APPLICATION_LAYER = 21
// LAST = 22
//

#define INITSTAGE_SIMU5G_LOCAL_PLUS_ONE                (inet::INITSTAGE_LOCAL+1)
#define INITSTAGE_SIMU5G_PHYSICAL_ENVIRONMENT          inet::INITSTAGE_PHYSICAL_ENVIRONMENT
#define INITSTAGE_SIMU5G_PHYSICAL_LAYER                inet::INITSTAGE_PHYSICAL_LAYER
#define INITSTAGE_SIMU5G_SINGLE_MOBILITY               inet::INITSTAGE_SINGLE_MOBILITY
#define INITSTAGE_SIMU5G_LINK_LAYER                    inet::INITSTAGE_LINK_LAYER
#define INITSTAGE_SIMU5G_NETWORK_CONFIGURATION         inet::INITSTAGE_NETWORK_CONFIGURATION
#define INITSTAGE_SIMU5G_NETWORK_LAYER                 inet::INITSTAGE_NETWORK_LAYER
#define INITSTAGE_SIMU5G_STATIC_ROUTING                inet::INITSTAGE_STATIC_ROUTING
#define INITSTAGE_SIMU5G_TRANSPORT_LAYER               inet::INITSTAGE_TRANSPORT_LAYER
#define INITSTAGE_SIMU5G_APPLICATION_LAYER_MINUS_ONE   (inet::INITSTAGE_APPLICATION_LAYER-1)
#define INITSTAGE_SIMU5G_APPLICATION_LAYER             inet::INITSTAGE_APPLICATION_LAYER
#define INITSTAGE_SIMU5G_LAST_MINUS_ONE                (inet::INITSTAGE_LAST-1)
#define INITSTAGE_SIMU5G_LAST                          inet::INITSTAGE_LAST

#endif
