#! /bin/sh
#
# usage: runtest [<testfile>...]
# without args, runs all *.test files in the current directory
#
# Requires SIMU5G_ROOT and INET_ROOT to be set (source the setenv scripts of
# both projects first), and the Simu5G and INET shared libraries to be built.
#

MODE=${MODE:-release}
if [ "$MODE" = "debug" ]; then D="_dbg"; else D=""; fi

TESTFILES=$*
if [ "x$TESTFILES" = "x" ]; then TESTFILES='*.test'; fi

if [ "x$INET_ROOT" = "x" ]; then echo "Error: INET_ROOT is not set"; exit 1; fi

if [ ! -d work ]; then mkdir work; fi

opp_test gen $OPT -v $TESTFILES || exit 1
echo

(cd work && opp_makemake -f --deep -o unittests -DINET_IMPORT \
     -I../lib -I../../../src -I$INET_ROOT/src \
     -L../../../src -lsimu5g'$(D)' \
     -L$INET_ROOT/src -lINET'$(D)' \
 && make MODE=$MODE -j$(nproc)) || exit 1
echo

# NED path is relative to work/<testname>/, the working directory of each test run
opp_test run -p unittests$D $OPT -v $TESTFILES \
    -a -n .:../../../../src:$INET_ROOT/src || exit 1
echo
echo Results can be found in ./work
